PhotoContest.Web/Models/ViewModels/ContestViewModel.cs
using System;
using System.ComponentModel;

namespace PhotoContest.Web.Models.ViewModels
{
    public class ContestViewModel
    {
        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the category.
        /// </summary>
        public CategoryViewModel Category { get; set; }

        /// <summary>
        /// Gets or sets the creator.
        /// </summary>
        public UserViewModel Creator { get; set; }

        /// <summary>
        /// Gets or sets the phase.
        /// </summary>
        public string Phase { get; set; }

        /// <summary>
        /// Gets or sets the cover URL.
        /// </summary>
        [DisplayName("Cover")]
        public string CoverURL { get; set; }

        /// <summary>
        /// Gets or sets the phase one finish time.
        /// </summary>
        public DateTime PhaseOneFinishTime { get; set; }

        /// <summary>
        /// Gets or sets the phase two finish time.
        /// </summary>
        public DateTime PhaseTwoFinishTime { get; set; }

        /// <summary>
        /// Gets or sets the remaining time phase one.
        /// </summary>
        public TimeSpan RemainingTimePhaseOne { get; set; }

        /// <summary>
        /// Gets or sets the remaining time phase two.
        /// </summary>
        public TimeSpan RemainingTimePhaseTwo { get; set; }
    }
}

PhotoContest.Web/Controllers/ContestsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PhotoContest.Services.Common;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.DTOs;
using PhotoContest.Services.Helpers.Enums;
using PhotoContest.Web.Models.InputModels;
using PhotoContest.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using X.PagedList;

namespace PhotoContest.Web.Controllers
{
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Authorize]
    public class ContestsController : Controller
    {
        #region Fields and Constructor

        /// <summary>
        /// The contest service
        /// </summary>
        private readonly IContestService contestService;
        /// <summary>
        /// The user service
        /// </summary>
        private readonly IUserService userService;
        /// <summary>
        /// The mapper
        /// </summary>
        private readonly IMapper mapper;
        /// <summary>
        /// The photo service
        /// </summary>
        private readonly IPhotoService photoService;
        /// <summary>
        /// The review service
        /// </summary>
        private readonly IReviewService reviewService;
        /// <summary>
        /// The category service
        /// </summary>
        private readonly ICategoryService categoryService;
        /// <summary>
        /// The toast notification
        /// </summary>
        private readonly IToastNotification toastNotification;
        /// <summary>
        /// The notification service
        /// </summary>
        private readonly INotificationService notificationService;

        /// <summary>
        /// Initializes a new instance of the <see cref="ContestsController"/> class.
        /// </summary>
        /// <param name="contestService">The contest service.</param>
        /// <param name="userService">The user service.</param>
        /// <param name="mapper">The mapper.</param>
        /// <param name="photoService">The photo service.</param>
        /// <param name="reviewService">The review service.</param>
        /// <param name="categoryService">The category service.</param>
        /// <param name="toastNotification">The toast notification.</param>
        /// <param name="notificationService">The notification service.</param>
        public ContestsController(IContestService contestService,
            IUserService userService,
            IMapper mapper,
            IPhotoService photoService,
            IReviewService reviewService,
            ICategoryService categoryService,
            IToastNotification toastNotification,
            INotificationService notificationService)
        {
            this.contestService = contestService;
            this.userService = userService;
            this.mapper = mapper;
            this.photoService = photoService;
            this.reviewService = reviewService;
            this.categoryService = categoryService;
            this.toastNotification = toastNotification;
            this.notificationService = notificationService;
        }

        #endregion

        /// <summary>
        /// Gets the user identifier.
        /// </summary>
        public Guid UserId { get => Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)); }

        #region Actions

        /// <summary>
        /// Receives photo create form and create it.
        /// </summary>
        /// <param name="model">The model.</param>
        [HttpPost]
        [Authorize(Roles = "Junkie")]
        public async Task<IActionResult> AddPhoto([FromForm] PhotoCreateModel model)
        {
            if (ModelState.IsValid)
            {
                PhotoDTO photoDTO = mapper.Map<PhotoDTO>(model);
                photoDTO.AuthorId = UserId;

                await photoService.AddPhotoAsync(photoDTO, model.ContestTitle);

                return RedirectToAction("Contest", new { contestTitle = model.ContestTitle });
            }

            // TODO:
            return BadRequest();
        }

        /// <summary>
        /// Add photo view.
        /// </summary>
        /// <param name="contestTitle">The contest title.</param>
        [HttpGet]
        [Authorize(Roles = "Junkie")]
        public IActionResult AddPhoto(string contestTitle)
        {
            ViewBag.ContestTitle = contestTitle;
            return View();
        }

        /// <summary>
        /// Add review view.
        /// </summary>
        /// <param name="model">The model.</param>
        [HttpPost]
        public async Task<IActionResult> AddReview([FromForm] ReviewCreateModel model)
        {
            if (ModelState.IsValid)
            {
                if (!model.FitsCategory)
                {
                    model.Score = 0;
                }

                model.AuthorId = UserId;
                ReviewDTO reviewDTO = mapper.Map<ReviewDTO>(model);
                ContestDTO contest = await contestService.GetAsync(model.ContestTitle);
                reviewDTO.ContestId = contest.Id;
                await reviewService.CreateAsync(reviewDTO);

                return RedirectToAction("Contest", new { contestTitle = model.ContestTitle });
            }

            return BadRequest();
        }

        /// <summary>
        /// Returns view with all contests listed.
        /// </summary>
        /// <param name="phase">The phase.</param>
        /// <param name="page">The page.</param>
        /// <param name="search">The search.</param>
        /// <param name="sortBy">The sort by.</param>
        /// <param name="orderBy">The order by.</param>
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> All(string phase, int? page, string search, SortBy? sortBy, OrderBy? orderBy)
        {
            ViewBag.Search = search;
            ViewBag.SortBy = sortBy;
            ViewBag.OrderBy = orderBy;
            ViewBag.Phase = phase;

            if (phase != null)
            {
                ICollection<ContestDTO> contestsByPhase = await contestService.GetByPhaseAsync(phase, search, sortBy, orderBy);

                ICollection<ContestViewModel> contestsByPhaseViewModels = mapper.Map<ICollection<ContestViewModel>>(contestsByPhase);
                IPagedList<ContestViewModel> pageModelByPhase = await contestsByPhaseViewModels.ToPagedListAsync(page ?? 1, 8);

                return View(pageModelByPhase);
            }

            ICollection<ContestDTO> contests = await contestService.GetAllAsync(search, sortBy, orderBy);

            ICollection<ContestViewModel> contestsViewModels = mapper.Map<ICollection<ContestViewModel>>(contests);
            IPagedList<ContestViewModel> pageModel = await contestsViewModels.ToPagedListAsync(page ?? 1, 8);

            return View(pageModel);
        }

        [HttpGet]
        [Authorize(Roles = "Junkie")]
        public async Task<IActionResult> FinishedContests(int? page, string search, SortBy? sortBy, OrderBy? orderBy)
        {
            ViewBag.Search = search;
            ViewBag.SortBy = sortBy;
            ViewBag.OrderBy = orderBy;

            ICollection<ContestDTO> contestsByPhase = await contestService.GetByPhaseAsync("finished", search, sortBy, orderBy);
            
            ICollection<ContestViewModel> contestsByPhaseViewModels = mapper.Map<ICollection<ContestViewModel>>(contestsByPhase);
            IPagedList<ContestViewModel> pageModelByPhase = await contestsByPhaseViewModels.ToPagedListAsync(page ?? 1, 5);

            return View(pageModelByPhase);
        }

        /// <summary>
        /// Returns page of contest with info for it
        /// </summary>
        /// <param name="contestTitle">The contest title.</param>
        [HttpGet]
        public async Task<IActionResult> Contest(string contestTitle)
        {
            ContestDTO contestDTO = await contestService.GetAsync(contestTitle);
            ContestViewModel model = mapper.Map<ContestViewModel>(contestDTO);
            model.CoverURL = contestDTO.Cover.ImageUrl;

            return View("Contest", model);
        }

        /// <summary>
        /// Create contest view.
        /// </summary>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var imagesDTOs = await photoService.GetImagesAsync();
            var imagesViews = mapper.Map<ICollection<ImageViewModel>>(imagesDTOs);

            var usersDTOs = await userService.GetAsync();
            var usersViews = mapper.Map<ICollection<UserViewModel>>(usersDTOs);

            ViewBag.Users = usersViews.Where(u => u.IsAdmin == false);
            ViewBag.Images = imagesViews;

            return View();
        }

        /// <summary>
        /// Creates the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(ContestCreateModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ContestDTO contestDTO = mapper.Map<ContestDTO>(model);
                    var category = await categoryService.GetCategoryAsync(model.CategoryName);
                    if (category == null)
                    {
                        category = new CategoryDTO() { Name = model.CategoryName };
                        await categoryService.CreateAsync(category);
                    }

                    contestDTO.CreatorId = UserId;
                    contestDTO.CategoryId = category.Id;
                    await contestService.CreateAsync(contestDTO);
                }
            }
            catch (Exception)
            {

PhotoContest.Web/Controllers/PhotosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhotoContest.Services.Contracts;
using PhotoContest.Web.Models.ViewModels;
using System;
using System.Threading.Tasks;

namespace PhotoContest.Web.Controllers
{
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Authorize]
    public class PhotosController : Controller
    {
        #region Fields and Constructor

        /// <summary>
        /// The photo service
        /// </summary>
        private readonly IPhotoService photoService;
        /// <summary>
        /// The mapper
        /// </summary>
        private readonly IMapper mapper;

        /// <summary>
        /// Initializes a new instance of the <see cref="PhotosController"/> class.
        /// </summary>
        /// <param name="photoService">The photo service.</param>
        /// <param name="mapper">The mapper.</param>
        public PhotosController(IPhotoService photoService,
            IMapper mapper)
        {
            this.photoService = photoService;
            this.mapper = mapper;
        }

        #endregion

        #region Actions

        /// <summary>
        /// Photo view action
        /// </summary>
        /// <param name="photoId">The photo identifier.</param>
        [HttpGet("photos/{photoId}")]
        public async Task<IActionResult> Photo(Guid photoId)
        {
            var photoDTO = await photoService.GetPhotoAsync(photoId);
            var model = mapper.Map<PhotoViewModel>(photoDTO);

            return View(model);
        }

        #endregion
    }
}

PhotoContest.Web/Controllers/UsersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.DTOs;
using PhotoContest.Web.Models.InputModels;
using PhotoContest.Web.Models.ViewModels;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PhotoContest.Web.Controllers
{
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Authorize]
    public class UsersController : Controller
    {
        /// <summary>
        /// The user service
        /// </summary>
        private readonly IUserService userService;
        /// <summary>
        /// The mapper
        /// </summary>
        private readonly IMapper mapper;
        /// <summary>
        /// The photo service
        /// </summary>
        private readonly IPhotoService photoService;
        /// <summary>
        /// The toast notification
        /// </summary>
        private readonly IToastNotification toastNotification;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersController"/> class.
        /// </summary>
        /// <param name="userService">The user service.</param>
        /// <param name="mapper">The mapper.</param>
        /// <param name="photoService">The photo service.</param>
        /// <param name="toastNotification">The toast notification.</param>
        public UsersController(IUserService userService, IMapper mapper, IPhotoService photoService, IToastNotification toastNotification)
        {
            this.userService = userService;
            this.mapper = mapper;
            this.photoService = photoService;
            this.toastNotification = toastNotification;
        }

        /// <summary>
        /// Action for logged user profile.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            string username = User.FindFirst(ClaimTypes.Name).Value;
            UserDTO userDTO = await userService.GetAsync(username);
            UserViewModel userViewModel = mapper.Map<UserViewModel>(userDTO);
            ICollection<PhotoDTO> userPhotos = await photoService.GetPhotosByParticipantAsync(username);
            float percentageProgressRank = (float)(1.0 * userViewModel.Points / (userViewModel.Points + userViewModel.PointsToNextRank)) * 100;
            string percentNumber = percentageProgressRank.ToString();

            ViewBag.UserPhotos = userPhotos;
            ViewBag.PercentNumber = percentNumber;

            return View(userViewModel);
        }

        /// <summary>
        /// Action for user profile
        /// </summary>
        /// <param name="username">The username.</param>
        [HttpGet]
        public async Task<IActionResult> UserProfile(string username)
        {
            UserDTO userDTO = await userService.GetAsync(username);
            UserViewModel userViewModel = mapper.Map<UserViewModel>(userDTO);
            ICollection<PhotoDTO> userPhotos = await photoService.GetPhotosByParticipantAsync(username);
            float percentageProgressRank = (float)(1.0 * userViewModel.Points / (userViewModel.Points + userViewModel.PointsToNextRank)) * 100;
            string percentNumber = percentageProgressRank.ToString();

            ViewBag.UserPhotos = userPhotos;
            ViewBag.PercentNumber = percentNumber;

            return View("ProfileUsername", userViewModel);
        }

        /// <summary>
        /// Renders view for Update form.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Update()
        {
            string user = User.FindFirst(ClaimTypes.Name).Value;
            UserDTO userDTO = await userService.GetAsync(user);
            UserViewModel userViewModel = mapper.Map<UserViewModel>(userDTO);
            UserUpdateModel userUpdateModel = mapper.Map<UserUpdateModel>(userDTO);
            ViewBag.Participant = userViewModel;

            return View(userUpdateModel);
        }

        /// <summary>
        /// Receives model from update form.
        /// </summary>
        /// <param name="model">The model.</param>
        [HttpPost]
        public async Task<IActionResult> Update(UserUpdateModel model)
        {
            if (ModelState.IsValid)
            {
                string participantName = User.FindFirst(ClaimTypes.Name).Value;
                UserDTO participantDTO = mapper.Map<UserDTO>(model);

                await userService.UpdateAsync(participantName, participantDTO);

                toastNotification.AddSuccessToastMessage("Greate! You have successfully updated your profile.");
                return RedirectToAction("Profile");
            }

            return BadRequest();
        }
    }
}

PhotoContest.Web/Views/Contests/AddPhoto.cshtml
@model PhotoCreateModel

<h4>To join contest "@ViewBag.ContestTitle", first have to upload your photo!</h4>
<hr />

<form asp-controller="Contests" asp-action="AddPhoto" method="post" enctype="multipart/form-data">

    <div asp-validation-summary="ModelOnly">
        <span>Please correct the following errors</span>
    </div>

    <div class="form-group row">
        <div class="col-4">
            <label asp-for="Title">Title</label>
            <input type="text" class="form-control" asp-for="Title" placeholder="Enter title">
            <span asp-validation-for="Title"></span>
        </div>
        <div class="col-4">
            <label asp-for="Description">Description</label>
            <input type="text" class="form-control" asp-for="Description" placeholder="Enter description">
            <span asp-validation-for="Description"></span>
        </div>
        <div class="col-4">
            <label asp-for="File">Photo</label>
            <input type="file" class="form-control-file" asp-for="File">
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-6">
            <input type="hidden" name="ContestTitle" value="@ViewBag.ContestTitle" />
            <button type="submit" value="Create" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PhotoContest.Web/Views/Contests/Contest.cshtml
@using PhotoContest.Services.Common
@using PhotoContest.Services.Contracts
@using System.Security.Claims
@inject IValidatorService validatorService
@inject IPhotoService photoService
@inject IContestService contestService
@model ContestViewModel

@{
    Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
}

<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    #myImg {
        border-radius: 5px;
        cursor: pointer;
        transition: 0.3s;
    }

        #myImg:hover {
            opacity: 0.7;
        }

    /* The Modal (background) */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        padding-top: 100px; /* Location of the box */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
    }

    /* Modal Content (image) */
    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
    }

    /* Caption of Modal Image */
    #caption {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
        text-align: center;
        color: #ccc;
        padding: 10px 0;
        height: 150px;
    }

    /* Add Animation */
    .modal-content, #caption {
        -webkit-animation-name: zoom;
        -webkit-animation-duration: 0.6s;
        animation-name: zoom;
        animation-duration: 0.6s;
    }

    /* The Close Button */
    .close {
        position: absolute;
        top: 15px;
        right: 35px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        transition: 0.3s;
    }

        .close:hover,
        .close:focus {
            color: #bbb;
            text-decoration: none;
            cursor: pointer;
        }
</style>

<div class="container">
    <div class="row">
        @*contest cover*@
        <div class="col">
            <img style="height: 350px; width: 700px" class="rounded float-left" src="@Model.CoverURL" />
        </div>
        @*contest info*@
        <div class="col-4.5">
            <div class="jumbotron" style="padding:10px; width: 340px">
                <partial name="ContestInfoTable" />
                @*join button / JUNKIE*@
                @if (!await validatorService.CheckParticipantAsync(Model.Title, userId)
                      && Model.Phase == Constants.Contest.PHASE_ONE_STRING
                      && !User.IsInRole("Admin")
                      && !await validatorService.CheckJuryAsync(Model.Title, userId))
                {
                    <div>
                        <a href="@Url.Action("Join", "Contests", new { ContestTitle = Model.Title, ParticipantId = userId })" type="button" class="btn btn-primary text-center">Join</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@*Phase Two / info for participants*@
@if (Model.Phase == Constants.Contest.PHASE_TWO_STRING &&
await validatorService.CheckParticipantAsync(Model.Title, userId))
{
    <hr />
    <h4>You participate in this contest. The contests is in Phase Two. Now jury reviews all photos.</h4>
    <hr />
}

@*uploaded photo info / only in Phase One, JUNKIE*@
@if (await validatorService.CheckParticipantAsync(Model.Title, userId)
&& (Model.Phase == Constants.Contest.PHASE_ONE_STRING || Model.Phase == Constants.Contest.PHASE_TWO_STRING)
&& !User.IsInRole("Admin")
&& !await validatorService.CheckJuryAsync(Model.Title, userId))
{
    if (await validatorService.CheckAlreadyUploadedPhotoAsync(Model.Title, userId))
    {
        <div class="container">
            <div class="row">
                <div class="col-3.5">
                    <partial name="UploadedPhotoInfo" model=@await photoService.GetByContestAndAuthorAsync(userId, Model.Title)>
                </div>
            </div>
        </div>
    }
}

@*review photos / only in Phase TWO, JURY*@
@if (await validatorService.CheckJuryAsync(Model.Title, userId))
{
    <hr />
    if (Model.Phase == Constants.Contest.PHASE_ONE_STRING)
    {
        <h4>You are jury in this contest. In Phase Two you can write reviews.</h4>
    }
    else if (Model.Phase == Constants.Contest.PHASE_TWO_STRING)
    {
        <div>
            @{ var photos = await photoService.GetByContestAsync(Model.Title);
                ViewData["ContestTitle"] = @Model.Title;
                var counter = 0;}
        </div>

        @foreach (var photo in photos)
        {
            if (validatorService.CheckAlreadyReviewedPhotoAsync(photo.Id, userId))
            {
                continue;
            }
            <div class="jumbotron">
                <div class="container">
                    <partial name="PhotoCardReviewForm" model="@photo" view-data=ViewData />
                </div>
            </div>
            counter++;
        }

        if (counter == 0)
        {
            <h4>No more photos!</h4>
        }
    }
}

@*Phase One / Jury and admins can view submitted photos but cannot rate them yet.*@
@if ((await validatorService.CheckJuryAsync(Model.Title, userId) || User.IsInRole("Admin")) &&
Model.Phase == Constants.Contest.PHASE_ONE_STRING)
{
    <div>
        @{var photos = await photoService.GetByContestAsync(Model.Title);}
    </div>
    <hr />
    if (photos.Count > 0)
    {
        @foreach (var photo in photos)
        {
            <div class="row">
                <div class="col-3.5">
                    <div class="card" style="width: 18rem;">
                        <div>
                            <img class="card-img-top" id="@photo.Id.ToString()" src="@photo.ImageUrl" alt="@photo.Title" style="width:100%;max-width:300px">
                            <!-- The Modal -->
                            <div id="myModal" class="modal">
                                <span class="close">&times;</span>
                                <img class="modal-content" id="img01">
                                <div id="caption"></div>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title" style="text-align: center">@photo.Title</h5>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card">
                        <div class="card-header">
                            Author
                        </div>
                        <div class="card-body">
                            <p class="card-text"><a href="@Url.Action(" UserProfile" ,"Users", new { username=@photo.Author.UserName })">@photo.Author.UserName</a></p>
                        </div>
                    </div>
                    <br />
                    <div class="card">
                        <div class="card-header">
                            Description
                        </div>
                        <div class="card-body">
                            <p class="card-text">@photo.Description</p>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the image and insert it inside the modal - use its "alt" text as a caption
    var img = document.getElementById("@photo.Id.ToString()");
    var modalImg = document.getElementById("img01");
    var captionText = document.getElementById("caption");
    img.onclick = function () {
        modal.style.display = "block";
        modalImg.src = this.src;
        captionText.innerHTML = this.alt;
    }

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on <span> (x), close the modal
    span.onclick = function () {
        modal.style.display = "none";
    }
            </script>
        }
    }
    else
    {
        <h4>No photos in this contest!</h4>
    }
}

@*Phase Finished*@
@if (Model.Phase == Constants.Contest.PHASE_FINISHED_STRING)
{
    <div>
        @{ var list = await contestService.GetWinners(Model.Title);
            var firstPlaced = list.FirstPlaced;
            var secondPlaced = list.SecondPaced;
            var thirdPlaced = list.ThirdPlaced;
            var lowPlaced = list.LowPlaced;
        }
    </div>

    <table class="table table-hover">
        <tr>
            <th>Place</th>
            <th>Photo</th>
            <th>Total Score</th>
        </tr>
        @foreach (var first in firstPlaced)
        {
            <tr>
                <td>1</td>
                <td>
                    <a href="@Url.Action("Photo" ,"Photos", new { photoId=first.PhotoId })">
                        <img width="200" src="@first.Photo.ImageUrl" />
                    </a>
                </td>
                <td>@first.Photo.Reviews.Sum(r => r.Score)</td>
            </tr>
        }
        @foreach (var second in secondPlaced)
        {
            <tr>
                <td>2</td>
                <td>
                    <a href="@Url.Action("Photo" ,"Photos", new { photoId=second.PhotoId })">
                        <img width="200" src="@second.Photo.ImageUrl" />
                    </a>
                </td>
                <td>@second.Photo.Reviews.Sum(r => r.Score)</td>
            </tr>
        }
        @foreach (var third in thirdPlaced)
        {
            <tr>
                <td>3</td>
                <td>
                    <a href="@Url.Action("Photo" ,"Photos", new { photoId=third.PhotoId })">
                        <img width="200" src="@third.Photo.ImageUrl" />
                    </a>
                </td>
                <td>@third.Photo.Reviews.Sum(r => r.Score)</td>
            </tr>
        }
        @{ int number = firstPlaced.Count + secondPlaced.Count + thirdPlaced.Count + 1; }
        @foreach (var lowPlace in lowPlaced)
        {
            <tr>    
                <td>@number</td>
                <td>
                    <a href="@Url.Action("Photo", "Photos", new { photoId = lowPlace.PhotoId })">
                        <img width="200" src="@lowPlace.Photo.ImageUrl" />
                    </a>
                </td>
                <td>@lowPlace.Photo.Reviews.Sum(r => r.Score)</td>
            </tr>              
            number = number + 1;
        }
    </table>
}